#!/bin/bash
./updlkt.sh 'lexDesire'  'lexAuxIWant'
./updlkt.sh 'lexToBe'  'lexAuxVerbBe'
./updlkt.sh 'lexWhat'  'lexAuxWhat'
./updlkt.sh 'lexIf'  'lexAuxPartIf'
./updlkt.sh 'auxObject'  'lexAuxAskFor'
./updlkt.sh 'lexDet'  'lexAuxDefArticle'
./updlkt.sh 'lexFor'  'lexAuxPartFor'
./updlkt.sh 'lexSubject'  'lexAuxPronoun'
./updlkt.sh 'lexSome'  'lexAuxUndefArticle'
./updlkt.sh 'null'  'lexAuxEmpty'
