#!/bin/bash
./updlkt.sh 'FEATURE'  'CLASSMODEL'
./updlkt.sh 'auxRelation'  'lexRelationAuxiliar'
./updlkt.sh 'Relation'  'Interaction'
./updlkt.sh 'Pardon'  'InterPardon'
./updlkt.sh 'Goodbye'  'InterFarewell'
./updlkt.sh 'Greeting'  'InterGreeting'
./updlkt.sh 'Please'  'InterPlease'
./updlkt.sh 'Thanks'  'InterThanks'
./updlkt.sh 'Hello'  'InterThanks'
