#!/bin/bash
./updlkt.sh 'IGoalType'  'OperPurposeDescriptor'
./updlkt.sh 'IGoalAction'  'OperPurposeVerb'
./updlkt.sh 'IGoalObject'  'OperPurposeNoun'
./updlkt.sh 'IGoal'  'OperPurpose'

./updlkt.sh 'CDomainType'  'ActScopeDescriptor'
./updlkt.sh 'CDomainTopic'  'ActScopeNoun'
./updlkt.sh 'CDomain'  'ActScope'

./updlkt.sh 'RDataClass'  'LinkedInfoDescriptor'
./updlkt.sh 'RData'  'LinkedInfo'

./updlkt.sh 'DateGo'  'DepartureDate'
./updlkt.sh 'DateBack'  'ReturnDate'
./updlkt.sh 'PrefTime'  'PeriodBefore'
./updlkt.sh 'DateNext'  'PeriodNext'
./updlkt.sh 'DatePrev'  'PeriodPrev'
./updlkt.sh 'RelTime'  'PeriodRelative'
./updlkt.sh 'Year'  'PeriodYear'
./updlkt.sh 'MonthName'  'PeriodMonthDesc'
./updlkt.sh 'Month'  'PeriodMonth'
./updlkt.sh 'WeekDayName'  'PeriodDayDesc'
./updlkt.sh 'Week'  'PeriodWeek'
./updlkt.sh 'RelDay'  'PeriodDayRelative'
./updlkt.sh 'Day'  'PeriodDay'
./updlkt.sh 'BlockToday'  'PeriodDayToday'
./updlkt.sh 'Block'  'PeriodDaySection'
./updlkt.sh 'Hour'  'PeriodHour'
./updlkt.sh 'MinuteVal'  'PeriodQuarter'
./updlkt.sh 'Minute'  'PeriodMinute'
./updlkt.sh 'Date'  'GlobalDate'
./updlkt.sh 'date-go'  'dateDeparture'
./updlkt.sh 'date-back'  'dateReturn'

./updlkt.sh 'DniFull'  'PersonalDescriptor'
./updlkt.sh 'DniNumber'  'PersonalRef'
./updlkt.sh 'DniDoc'  'PersonalDocument'
./updlkt.sh 'DniId'  'PersonalIdentity'
./updlkt.sh 'DniIs'  'PersonalAuxVerb'
./updlkt.sh 'Dni'  'PersonalId'
./updlkt.sh 'dni'  'personalid'

./updlkt.sh 'FModeWay'  'FlightTypeWay'
./updlkt.sh 'FModeGo'  'FlightTypeDeparture'
./updlkt.sh 'FModeBack'  'FlightTypeReturn'
./updlkt.sh 'FModeNumber'  'FlightId'
./updlkt.sh 'FMode'  'FlightType'
