#!/bin/bash
./updlkt.sh 'WTaskType'  'ProcessStage'
./updlkt.sh 'TStageBuyTicket'  'PhaseControlGetTicket'
./updlkt.sh 'TStageConsult'  'PhaseControlSearchPoints'
./updlkt.sh 'WTask'  'ProcessControl'

./updlkt.sh 'consult-point'  'searchPoints'
./updlkt.sh 'buy-flight'  'getTicket'
./updlkt.sh 'cancel-flight'  'cancelTicket'
./updlkt.sh 'consult-flight'  'searchTicket'
./updlkt.sh 'modify-flight'  'changeTicket'

./updlkt.sh 'look-route-origin'  'phaseSeekPlaceDeparture'
./updlkt.sh 'look-route-destination'  'phaseSeekPlaceDestination'
./updlkt.sh 'look-dateDeparture'  'phaseSeekDateDeparture'
./updlkt.sh 'check-dateDeparture'  'phaseVerifyDateDeparture'

./updlkt.sh 'look-personalid'  'phaseSeekPersonalId'
./updlkt.sh 'request-user-info'  'phaseAskPersonalId'
./updlkt.sh 'check-user-info'  'phaseVerifyPersonalId'
./updlkt.sh 'error-user-notfound'  'phaseInformPersonalIdNonExistent'
./updlkt.sh 'error-user-id'  'phaseInformPersonalIdInvalid'
./updlkt.sh 'error-user-incoherence'  'phasePersonalIdError'
./updlkt.sh 'look-personalid-correct'  'phaseSearchPersonalId'
./updlkt.sh 'inform-point'  'phaseInformPoints'

./updlkt.sh 'look-route-origin'  'phaseSeekPlaceDeparture'
./updlkt.sh 'check-route-origin'  'phaseVerifyPlaceDeparture'
./updlkt.sh 'error-route-origin'  'phaseInvalidPlaceDeparture'
./updlkt.sh 'error-route-destination'  'phaseInvalidPlaceDestination'
./updlkt.sh 'error-route'  'phaseInvalidRoute'
./updlkt.sh 'look-route-destination'  'phaseSeekPlaceDestination'
./updlkt.sh 'compare-route-origin-destination'  'phaseValidateWholeRoute'
./updlkt.sh 'check-route-destination'  'phaseVerifyPlaceDestination'
./updlkt.sh 'look-dateDeparture'  'phaseSeekDateDeparture'
./updlkt.sh 'check-dateDeparture'  'phaseVerifyDateDeparture'
./updlkt.sh 'error-dateDeparture'  'phaseInvalidDateDeparture'
./updlkt.sh 'request-flt-info-go'  'phaseAskFligthGo'
./updlkt.sh 'error-flt-notfound-go'  'phaseNotAvailabilityFligthGo'
./updlkt.sh 'inform-flt-go'  'phaseInformFlightGo'
./updlkt.sh 'move-flt-go'  'phaseContinueFlightGo'
./updlkt.sh 'informmove-flt-go'  'phaseInformContinueFlightGo'
./updlkt.sh 'errormove-flt-go'  'phaseErrorContinueFlightGo'
./updlkt.sh 'look-dateReturn'  'phaseSeekDateReturn'
./updlkt.sh 'check-dateReturn'  'phaseVerifyDateReturn'
./updlkt.sh 'error-dateReturn'  'phaseInvalidDateReturn'
./updlkt.sh 'request-flt-info-back'  'phaseAskFligthReturn'
./updlkt.sh 'error-flt-notfound-back'  'phaseNotAvailabilityFlightReturn'
./updlkt.sh 'inform-flt-back'  'phaseInformFlightReturn'
./updlkt.sh 'move-flt-back'  'phaseContinueFlightReturn'
./updlkt.sh 'informmove-flt-back'  'phaseInformContinueFlightReturn'
./updlkt.sh 'errormove-flt-back'  'phaseErrorContinueFlightReturn'

